      SUBROUTINE CALJUL(MONTH,IDAY,IYEAR,JDAY)
!    CALJUL RETURNS THE JULIAN DAY, GIVEN THE CALENDAR DATE IN DAY-MONTH-YEAR.
!  THE JULIAN DAY IS THE DAY NUMBER WITHIN THE YEAR (JANUARY 1 IS DAY, FEBRUARY 1
!  IS DAY 32, ETC.)
!      LEAP YEARS ARE ACCOUNTED FOR.
!
!  ARGUMENTS:
!     MONTH  - THE MONTH NUMBER OF THE CALENDAR DAY TO BE CONVERTED.
!     IDAY   - THE DAY NUMBER OF THE CALENDAR DAY TO BE CONVERTED.
!     IYEAR  - THE YEAR OF THE DAY TO BE CONVERTED.
!     JDAY   - THE JULIAN DAY RETURNED FROM CALJUL.
!
!  CONVERTED FROM THE IBM1800 SYSTEM BY PAUL HENKART, SCRIPPS INSTITUTION OF
!  OCEANOGRAPHY, 28 OCTOBER 1980
!
!  mod 1 Apr 10 - Get rid of arithmetic IF
!
      DIMENSION NDAYS(12)
      DATA NDAYS /0,31,59,90,120,151,181,212,243,273,304,334/
!
      JDAY=NDAYS(MONTH)+IDAY
!
!     TAKE CARE OF LEAP YEARS
!
!      IF(IYEAR-IYEAR/4*4) 3,1,3
!1     IF(MONTH-2) 3,3,2
!2     JDAY=JDAY+1
      IF( iyear .NE. iyear/4*4 ) RETURN
      IF( month .GT. 2 ) jday = jday + 1
3     RETURN
      END
