      SUBROUTINE MAXSC(TRACE,DEFF,NSAMPS,ITYPE,PEAK,TROUGH)
!****
!    A SUBROUTINE TO SCALE AN ARRAY SO THAT SOME SAMPLE IS +/- DEFF*RNIBS BIG.
! THIS IS A SCALING ROUTINE FOR VERSATEC SEISMIC TRACE PLOTS.
! ARGUMENTS:
!        TRACE  - THE ARRAY CONTAINING THE DATA.  THE SCALED DATA IS PLACED IN
!                 TRACE ALSO, THEREBY CLOBBERING THE ARRAY.
!        DEF    - THE VALUE OF THE LARGEST VALUE AFTER SCALING.  THE LARGEST
!                 VALUE WILL BE SCALED TO DEF.  ( ALSO THE DEFLECTION OF A TRACE
!        NSAMPS - NUMBER OF SAMPLES (16 BIT INTEGER)
!        ITYPE  - TYPE OF SCALE
!               =1, DELECTION IS MEASURED FROM THE PEAK TO THE ZERO LINE
!               =2, DEFLECTION IS MEASURED AS THE DISTANCE BETWEEN PEAK AND TROUGH
!        PEAK   - THE LARGEST POSITIVE VALUE WITIN ARRAY TRACE
!        TROUGH - THE MOST NEGATIVE VALUE IN ARRAY TRACE
!   NOTE THAT BOTH PEAK AND TROUGH ARE VALUES RETURNED BY MAXSC, THAT IS THEY
!  ARE SET BY MAXSC.
!     PAUL HENKART, SCRIPPS, DECEMBER 1978
!  mod 31 Mar 10 - get rid of aritmetic IF
!****
      DIMENSION TRACE(1)
      COMMON /VERSAT/NIBS,RNIBS
      COMMON /MAXSCS/NPRMUL,RMULT
      SAVE
      DATA N/0/, rmult1/0./
      PEAK=0.
      TROUGH=0.
      IF(RMULT1.NE.0.) RMULT=RMULT1                                      ! TRPLOT4 SAVES THE ORIGINAL VALUE OF RMULT
      IF(RMULT.LE.0.) GO TO 5
      X=RMULT
      GO TO 205
    5 DEF=DEFF*RNIBS
!      DO 100 I=1,NSAMPS
!      IF(TRACE(I))10,100,50
!   10 IF(TRACE(I).GE.TROUGH) GO TO 100
!      TROUGH=TRACE(I)
!      GO TO 100
!   50 IF(TRACE(I).LE.PEAK) GO TO 100
!      PEAK=TRACE(I)
!  100 CONTINUE
      DO i = 1, nsamps
         IF( trace(i) .LT. 0 ) THEN
             IF( trace(i) .LT. trough ) trough = trace(i)
         ELSE
             IF( trace(i) .GT. peak ) peak = trace(i)
         ENDIF
      ENDDO
      GO TO (200,300), ITYPE
  200 IF(PEAK.EQ.0.) RETURN                                              ! WHY MULTIPLY EVERYTHING BY 0
      X=DEF/PEAK
  205 CONTINUE
      IF(RMULT.LT.0.) GO TO 206
      IF(NPRMUL.EQ.0) GO TO 208
      IF(NPRMUL.LE.N) GO TO 208
  206 N=N+1
      PRINT 207,X
  207 FORMAT(' THE PLOT MULTIPLIER IS ',G10.4)
      IF(RMULT.LT.0.) RMULT1=X
  208 DO I=1,NSAMPS
  210 TRACE(I)=TRACE(I)*X
      ENDDO
      RETURN
  300 CONTINUE
      IF(PEAK-TROUGH.EQ.0.) RETURN                                       ! WHY MULTIPLY BY ZEROES
      X=DEF/AMAX1(ABS(PEAK),ABS(TROUGH))
      GO TO 205
      END
