      SUBROUTINE RECTC(N,BUF,AMP,PHZ)
!    RECTC COMPUTES THE RECTANGULAR COORDINATES FROM THE POLAR COORDINATES.
!   ARGUMENTS:
!  N    - THE NUMBER OF COORDINATES TO CONVERT. AMP AND PHZ MUST CONTAIN N POINTS.
!  BUF  - THE REAL ARRAY N*2 LONG CONTAINING THE RECTANGULAR COORDINATES.
!  AMP  - THE ARRAY CONTAINING THE AMPLITUDE SPECTRUM.
!  PHZ  - THE ARRAY CONTAINING THE PHASE SPECTRUN.
!
      DIMENSION BUF(1),AMP(1),PHZ(1)
      M=1
      DO I=1,N
         ANGLE = PHZ(I)
         BUF(M) = AMP(I)*COS(ANGLE)
         BUF(M+1) = AMP(I)*SIN(ANGLE)
  100    M=M+2
      ENDDO
      RETURN
      END
