      SUBROUTINE SWAP32(BUF,N)
!     SWAP32 SWAPS THE 4 BYTES WITHIN EACH 32 BIT WORD OF ARRAY BUF.
!  THIS ROUTINE IS USEFUL FOR CONVERTING DEC 32 BIT INTEGERS TO OTHER COMPUTER
!  INTEGER FORMATS (OR VICE VERSA).
!
!  ARGUMENTS:
!     BUF - THE ARRAY TO BE CONVERTED.
!     N   - THE NUMBER OF 32 BIT WORDS TO BE CONVERTED. INTEGER*4
!
!  COPYRIGHT: PAUL HENKART, SCRIPPS INSTITUTION OF OCEANOGRAPHY, 11 APRIL 1982
!
      CHARACTER*1 BUF(1),A(4)
!
      J=1
      DO I=1,N
      A(1)=BUF(J)
      A(2)=BUF(J+1)
      A(3)=BUF(J+2)
      A(4)=BUF(J+3)
      BUF(J)=A(4)
      BUF(J+1)=A(3)
      BUF(J+2)=A(2)
      BUF(J+3)=A(1)
  200 J=J+4 
      ENDDO
      RETURN
      END
