      SUBROUTINE SWAP16(BUF,N)
!     F77 SWAP16 SWAPS THE 2 BYTES WITHIN EACH 16 BIT WORD OF ARRAY BUF.
!  THIS ROUTINE IS USEFUL FOR CONVERTING DEC 16 BIT INTEGERS TO OTHER COMPUTER
!  INTEGER FORMATS (OR VICE VERSA).
!
!  ARGUMENTS:
!     BUF - THE ARRAY TO BE CONVERTED.
!     N   - THE NUMBER OF 16 BIT WORDS TO BE CONVERTED.   INTEGER*4
!
!  COPYRIGHT: PAUL HENKART, SCRIPPS INSTITUTION OF OCEANOGRAPHY, 11 APRIL 1982
!
      CHARACTER*1 BUF(1),A
!
      J=1
      DO 200 I=1,N
      A=BUF(J)
      BUF(J)=BUF(J+1)
      BUF(J+1)=A
      J=J+2
  200 CONTINUE
      RETURN
      END
