      SUBROUTINE SWAP64(BUF,N)
!     SWAP64 SWAPS THE 8 BYTES WITHIN EACH 64 BIT WORD OF ARRAY BUF.
!  THIS ROUTINE IS USEFUL FOR CONVERTING LITTLE ENDIAN (E.G> INTEL)
!  64 BIT DOUBLE PRECISION IEEE WORDS TO BIG ENDIAN (E.G. SUN) ORDER.
!
!  ARGUMENTS:
!     BUF - THE ARRAY TO BE CONVERTED.
!     N   - THE NUMBER OF 64 BIT WORDS TO BE CONVERTED. INTEGER*4
!
!  COPYRIGHT: PAUL HENKART, SCRIPPS INSTITUTION OF OCEANOGRAPHY
!
      CHARACTER*1 BUF(1),A(8)
!
      J=1
      DO 200 I=1,N
      A(1)=BUF(J)
      A(2)=BUF(J+1)
      A(3)=BUF(J+2)
      A(4)=BUF(J+3)
      A(5)=BUF(J+4)
      A(6)=BUF(J+5)
      A(7)=BUF(J+6)
      A(8)=BUF(J+7)
      BUF(J)=A(8)
      BUF(J+1)=A(7)
      BUF(J+2)=A(6)
      BUF(J+3)=A(5)
      BUF(J+4)=A(4)
      BUF(J+5)=A(3)
      BUF(J+6)=A(2)
      BUF(J+7)=A(1)
      J=J+8
  200 CONTINUE
      RETURN
      END
