      SUBROUTINE VELPLT(IBUF,NSAMPS,VEL,VTUPLE)
!     VELPLT PUTS THE VELOCITY SPECTRA SEMBLANCE IN THE VELDAT COMMON ARRAY
!  FOR EACH TRACE SENT IT.  THE SEMBLANCE MUST BE IN IBUF AS 16 BIT INTEGERS.
!  THE VELDAT WILL CONTAIN HOLLERITHS SUITABLE TO BE PRINTED WITH AN A1 FORMAT.
!  THIS IS TABLE DRIVEN BECAUSE ENCODES ARE NOTORIOUSLY SLOW AND EXPENSIVE!
!
!  ARGUMENTS:
!  IBUF  - THE ARRAY OF SEMBLANCES (32 BIT INTEGERS).  IT IS ASSUMED THAT EVERY
!          CALL TO VELPLT STARTS AT THE SAME TIME.
!  NSAMPS - THE NUMBER OF SAMPLES IN THE IBUF ARRAY THAT NEED TO BE PLOTTED.
!  VEL    - THE VELOCITY ASSOCIATED WITH THE ARRAY IN IBUF.  THIS IS USED IN
!           CONJUNCTION WITH VTUPLE TO FIGURE OUT WHICH COLUMN TO USE.
!  VTUPLE - A 3 WORD ARRAY CONTAINING THE START VELOCITY OF THE ANALYSIS, THE
!           END VELOCITY, AND THE NUMBER OF COLUMNS BETWEEN THEM.
!
!
!  WRITTEN AND COPYRIGHTED BY:
!  PAUL HENKART, SCRIPPS INSTITUTION OF OCEANOGRAPHY, 21 MAY 1981
!  ALL RIGHTS ARE RESERVED BY THE AUTHOR.  PERMISSION TO COPY OR REPRODUCE THIS
!  SUBROUTINE, BY COMPUTER OR OTHER MEANS, MAY BE OBTAINED ONLY FROM THE AUTHOR.
!
      DIMENSION VTUPLE(111)
      INTEGER*4 IBUF(111)
      COMMON /VELDAT/IA(900)
      CHARACTER*132 IA
      SAVE
      LOGICAL FIRST
      COMMON /VPLT/ IALPHA(50)
      CHARACTER*1 IALPHA
      DATA FIRST/.TRUE./
!
      IF(.NOT.FIRST) GO TO 10
      FIRST=.FALSE.
      VINC=(VTUPLE(2)-VTUPLE(1))/(VTUPLE(3)-1)
   10 CONTINUE
      ICOL=(VEL-VTUPLE(1))/VINC + 1                                     ! FIGURE OUT WHAT COLUMN THIS VELOCITY IS
      DO 100 I=1,NSAMPS
      IA(I)(ICOL:ICOL)=IALPHA(IBUF(I)+1)
  100 CONTINUE
      RETURN
      END
